{% set name = "pynastran" %}
{% set tag = "v1.4.1" %}
{% if tag.startswith('v') %}
{% set version = tag[ 1: ] %}
{% else %}
{% set version = tag %}
{% endif %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/SteveDoyle2/pyNastran.git
  git_rev: "{{ tag }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.9.0
  run:
    - python >=3.9.0
    - numpy
    - scipy
    - matplotlib
    - docopt-ng
    - cpylog
    - nptyping >=2.0
    - imageio
    - pillow
    - qtpy

about:
  home: https://github.com/SteveDoyle2/pyNastran
  license: BSD
  license_family: BSD
  license_file: LICENSE.md
  summary: "Nastran BDF/F06/OP2/OP4 File reader/editor/writer/viewer"
  doc_url: https://pynastran-git.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/SteveDoyle2/pyNastran

extra:
  recipe-maintainers:
    - your-github-id-here
