{% set name = "tecio" %}
{% set version = "2021.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: tecio.tgz
  url: https://tecplot.azureedge.net/products/tecio/2021r2/tecio.tgz
  sha256: b0dbc1ce69d1ad968fbc5e4569cdf454908d96e3019e41f2e96f92280d82afc6

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}  # Cf comment above
  host:
    - boost
  run:
    - boost

test:
  commands:
    - test -f $PREFIX/lib/libtecio.a

about:
  home: https://www.tecplot.com/
  license: Other
  license_file: teciosrc/tecio_license_agreement.txt
  summary: 'Tecplot file processing library.'
  description: |
    The TecIO library allows third-party applications to read and write Tecplot file format. You’ll find an easier-to-use API for writing SZL files, in addition to less memory needed. The memory savings is due to more flexibility in the order the API accepts data. TecIO supports 64-bit indexing which allows individual zones to exceed two billion nodes!.
  doc_url: https://tecplot.azureedge.net/products/360/current/360_data_format_guide.pdf
